vim.g.transparent_enabled = false

require("transparent").setup {
  groups = { -- table: default groups
    "Normal",
    "NormalNC",
    "Comment",
    "Constant",
    "Special",
    "Identifier",
    "Statement",
    "PreProc",
    "Type",
    "Underlined",
    "Todo",
    "String",
    "Function",
    "Conditional",
    "Repeat",
    "Operator",
    "Structure",
    "LineNr",
    "NonText",
    "SignColumn",
    "CursorLineNr",
    "EndOfBuffer",
  },
  extra_groups = {
    "VertSplit",

    "toggleterm",
    "ZenBg",
    "MasonNormal",

    "NvimTreeNormal",
    "NvimTreeWinSeparator",
    "NvimTreeStatuslineNc",
    "NvimTreeEndOfBuffer",

    "TerminalBorder",
    "TerminalNormal",
    "FloatermBorder",
    "Floaterm",

    "LspFloatWinNormal",
    "Normal",
    "NormalFloat",
    "FloatBorder",
    "TelescopeNormal",
    "TelescopeBorder",
    "TelescopePromptBorder",
    "SagaBorder",
    "SagaNormal",
  },
  exclude_groups = {},
}
